### ISSUE TITLE
Understanding the UnSupervised Dataloader

### ISSUE THREAD

**Issue by nbansal90** [Jia-Research-Lab/Context-Aware-Consistency#15]
Hey @X-Lai ,

Thank you for sharing your work!

I was able to set up the repository and run the experiments in accordance with the steps provided. However , I am finding it difficult to understand some part of the code related to unsupervised data loader. Please find my queries below:

1. Why have we chosen 320x320 for VOC dataset and 720x720 for Cityscapes? Just wanted to understand the rational behind it.
2. In code, in file `dataloaders/voc.py`:
```
        overlap1_ul = [max(0, y2-y1), max(0, x2-x1)]
        overlap1_br = [min(self.crop_size, self.crop_size+y2-y1, h//self.stride * self.stride), min(self.crop_size, self.crop_size+x2-x1, w//self.stride * self.stride)]
        overlap2_ul = [max(0, y1-y2), max(0, x1-x2)]
        overlap2_br = [min(self.crop_size, self.crop_size+y1-y2, h//self.stride * self.stride), min(self.crop_size, self.crop_size+x1-x2, w//self.stride * self.stride)]
```

I am not quite able to understand the utility of ```self.stride```, why is this necessary and what exactly does `overlap1_ul` and  `overlap1_br` represent

Regards
Nitin

**Comment by X-Lai** [comment]
Thanks for your interest in our work.
1. We choose 320x320 crop for VOC just because the previous works such as CCT uses this setting, and we just follow them. For Cityscapes, we follow the common practice, i.e., 720x720 crop.
2. `overlap1_ul` and `overlap1_br` represent the relative coordinates of the upper-left corner and bottom-right corner of the overlapping region (relative to the first crop). And `self.stride` is set to 8 in our experiments, which represents the stride of the feature maps, i.e., `phi_u1` and `phi_u2`.

Hope the reply helps.

**Comment by X-Lai** [comment]
I will close this issue. If you have further question, feel free to reopen it.
