### ISSUE TITLE
Why iters are fixed for semi experiment? (like 1157)

### ISSUE THREAD

**Issue by TiankaiHang** [Jia-Research-Lab/Context-Aware-Consistency#8]
Hi,
as the question, why iters are fixed?
If it is fixed, and the iters to run over the epoch are less than the fixed number. Maybe it's not suitable to call that the whole training process runs 80 epochs.

An I also want to ask how much time it takes to train the models (80 epochs, fixed iters, voc/city dataset).

Thanks!!

**Comment by X-Lai** [comment]
Thanks for your comment. 

Fixing the number of training steps is for the fair comparison among the models trained with 1/16, 1/8 and 1/4 labeled data. Because if we don't fix the number of training steps, the model with 1/16 labeled data will be trained longer than others. If you want, feel free to adjust the training steps by yourself. 

It takes about 24 hours with 2 RTX2080Ti GPUs for VOC, and about 30 hours with 4 RTX2080Ti GPUs for Cityscapes.
